### ISSUE TITLE
Memory leak on src/examples/example_1_connect.php

### ISSUE THREAD

**Issue by k1r0s** [saleslayer/Sales_Layer_PHP_SDK#14]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /usr/src/myapp/saleslayer/SalesLayer-Conn.php on line 709

**Comment by k1r0s** [comment]
I can share connection keys by email if requested

**Comment by k1r0s** [comment]
on top of that **executing only these lines** has the same outcome:

```php
	if (!class_exists('SalesLayer_Conn')) require dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'SalesLayer-Conn.php';


    $connector_id = 'XXXXXXXXXXX';
	$secret_key   = 'XXXXXXXXXXXXXXXXXXXX;

	// Instantiate the class
	$SLconn = new SalesLayer_Conn($connector_id, $secret_key); // memory leak has to be over here

	$SLconn->set_API_version('1.17');

	$SLconn->get_info();

```

**Comment by juliolaguna** [comment]
Hi Ciro.

You can try increasing memory limit for php main execution script (or directly on php.ini configuration).
I did some tests under your account and it's enough increasing it to 256M. But 512 would be better choice to be sure.

*_The amount of memory the SDK needs depends a lot on the amount and complexity of data to handle returned by the API._

You can insert this line at the beginning of your script.

`ini_set('memory_limit', '512M');`

I usually use 

`ini_set('memory_limit', '-1');  //No limit. Use available memory if needed. Be careful`

You can also play with execution script values like :

`ini_set('max_execution_time', 300);`

where 300 is the max number of execution script seconds.

**Can you check this solution and tell me if all is working as expected?**

------------------------------------

On the other hand another good solution for managing big data amounts , is to use our v18 API, which can handle results pagination limiting the output data , but at a little more complex script solution.

*_However, you may need to increase the memory available for execution depending on the data structure and complexity of your connector._

You can fin more information on [API Support](https://support.saleslayer.com/api/introduction)


If I can continue helping you, do not hesitate to post new comments.

Thanks for your comments, are very appreciated.

**Comment by k1r0s** [comment]
thx
